### ISSUE TITLE
Dates not ordered correctly

### ISSUE THREAD

**Issue by 0x1d1z3r** [luketurner/PersonalPVT#3]
Hello,
![wrongorder](https://github.com/luketurner/PersonalPVT/assets/88399502/cf7927b0-ebfc-4e0d-86d8-cfe67890dfbd)
I took tests over multiple days and they aren't ordered correctly and it thinks i only took tests on only one day when it was in fact over a span of three days.

Thanks,
Daniel

**Comment by 0x1d1z3r** [comment]
This also affects the results graph , the  data points are ordered in the same way.

**Comment by luketurner** [comment]
Hi, thanks for the bug report! I see what you mean, seems rather strange.

I should be able to look into fixing this tonight/tomorrow!

**Comment by luketurner** [comment]
Should be fixed now -- trials are sorted in chronological order (most recent on the right) in the results graph, and reverse-chronological (most recent on the top) in the sidebar. This also seems to have fixed the date calculation. Let me know if there are any problems!

**Comment by luketurner** [comment]
You may need to do a hard refresh (Ctrl+F5) to get the updated version
